name: Sync Developer with Master

on:
  push:
    branches:
      - releases  # Trigger when code is pushed to master
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Merge master into developer
        run: |
          git checkout developer
          git pull origin developer
          git merge origin/releases || echo "Merge conflict detected" > conflict.txt

      - name: Push changes if merge is successful
        if: success()
        run: |
          git push origin developer

      - name: Send email notification on conflict
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Merge Conflict Alert in Developer Branch"
          body: "Merge conflict detected while merging master into developer. Please resolve it manually."
          to: "dev-team@example.com"
          from: "CI Bot <ci@example.com>"
