name: Auto Merge Releases to Developer

on:
  push:
    branches:
      - releases

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Merge releases into developer
        run: |
          git checkout developer
          git merge releases --allow-unrelated-histories --no-edit
          git push origin developer

      - name: Handle Merge Conflicts
        if: failure() && github.ref == 'refs/heads/releases'
        run: |
          echo "::error::Merge conflict occurred. Please resolve manually."
          exit 1
